import getRandomItemFromArray from '../../getRandomItemFromArray'

const QUOTES = [
  'A foolish man complains about the hole in his pocket. A wise man uses that hole to scratch his balls...',
  'They say about 80% of men have a girlfriend. That means that the other 20% still have a brain. Stay on that grind kings, keep your head up and remember: Girl spelled backwards is liar',
  '#Up #your #grindset',
  `I stopped taking my "antipsychotic medication" and now there are five voices in my head telling me to rise and grind every morning.`,
  'NO DISTRACTIONS 💯💯💯',
  "I don't shower because my sweat cleans my body for me",
  "I never change my underwear because I don't let shit bother me.",
  'Eat child flesh to maintain youth so you can have more time to grind',
  "Steal a homeless person's money, the sudden loss of money will force him to grind twice as hard (blessing in disguise)",
  'Read all 120 pages of term and condition then disagree it',
  'Rub your hands together before shaking hands with someone so you can steal their electrons',
  'If the boss fires you, set the office on fire too',
  'She didn’t leave you on read, you left her speechless',
  'If you ever get rejected from art school commit genocide',
  'If she sees you as her brother, u shall go for her mother',
  'Sleep at 3am and wake up at 2am and hence get -1 hour of sleep so you get 25 hours a day to grind',
  'Quit art school, and become a leader in society',
  "Don't ever date a girl who doesn't respect your wife",
  "Never drink water, piss contains more nutrients and doesn't cost anything",
  'Always say ggez in combat whether you lose or win',
  `gg does not mean "good game" anymore, but "get grindset"`,
  'Make alphas feel like they’re betas',
  'Never search the actual name of the song',
  'Get rid of your vital organs. Only vital thing for a sigma male is his grind',
  'Eat all your food a week in advance to save time',
  'Demotivate and beat people if they try to stand out...only sigma stays at the top',
  'Never wear pants, the shit in them weighs you down',
  'Flex your house keys to the homeless man to assert dominance',
  'Never make facial expressions they use to much energy',
  'Escape to Argentina and fool the entire world',
  'Respect all sigma rules and sigma males',
  `Don't just keep the violence domestic, take that shit international`,
  'If the teacher bends over trying to help another student, always take advantage of your surroundings',
  'If you didn’t go for the head, give them head',
  'Get free scrap metal by getting shot',
  'Don’t think outside the box, shit in the box.',
  'If your kid disobeys you just murder him and start again. Never endanger the tribe.',
  'You can’t spell ‘female’, without male.',
  'Force your heavily traumatised 14 year old son into a robot and have him fight lovecraftian aliens',
  'Clothes are a waste of money. Be naked.',
  'A true sigma male never loses his virginity because he never loses.',
  'If your grandma is bent over, is it a vulnerability or an opportunity?',
  'Girl spelled backwards is liar',
  'When someone pisses in your tea, down it.',
  'Never, under any circumstances, let people enjoy things.',
  'Start a war to distract everyone from their misery.',
  'Disregard female acquire currency',
  "Don't let casual racism be a part of your life, go competitive.",
  'Simply do math to show off your mental prowess to attract women',
  `The phrase “it's just a game” is such a weak mindset. You are ok with what happened, losing, imperfection of a craft. When you stop getting angry after losing, you've lost twice. There's always something to learn, and always room for improvement, never settle.`,
  'I don’t ever take showers, because my bank account is already clean',
  'Stay awake 25 hours a day, sleep is a waste of time”',
  "Don't take your schizophrenia pills. Take the red pill.",
  "I'm right, you are wrong. I'm funny, you are not",
  "Don't eat food since you can't let it slow down your grindsest.",
  "Don't ask who candice is",
  'Insult everyone equally so nobody can call you racist',
  'If you see a person in a wheelchair. Tell him to stop being lazy while throwing his lazychair away',
  'Child slaves are much cheaper than paid workers',
  'People are assets',
  "Age is just a number, don't let it stop you.",
  'Financial stability is more important than mental stability',
  'Lack of money is the root of all weaknesses.',
  'The only number that dictates my actions is my bank account, not age.',
  'Attack a random kid if he looks at the wrong way.',
  "Don't clean your room. Adapting to messy conditions makes you stronger and saves more time to hustle. 💯💸🚬",
  'Shit now, wipe later. Never flush 💯',
  'Feed exclusively on your own seed. Real sigmas are fully self reliant',
  'If you are born in a world where you are forced to shit, nothing is forcing for you to wipe.',
  'Cut your brakes. Just like the grind, your car should never stop.',
  'The bible never said anything about tax evasion 💯🙏',
  'Kick over a homeless mans coin cup, the world doesn’t wait for anybody to change.',
  "Don't take your meds, listen to the voices",
  'Many Fools beat their meat, But only the Strongest defeats it',
  "Tell people a joke - keep the punchline to yourself. The sigma male doesn't need to hear others laugh",
  'Once you are done with a dumbbell rep drop them on your feet. It will make them larger and you will assert dominance over your rivals more easily',
  'A Beta male puts the milk first, an Alpha male puts the cereal first, I put my money first',
  'Troll the working class by reducing the minimum wage and increasing housing prices, passive income is an important part of the grind',
  'Sell your parents house - passive income is an important part of the grind',
  "Don't think outside the box, buy the box",
  'I just flashed my plumber. He left... And I got my sink fixed for free. 🥂',
  "Poo your pants in public and don't explain yourself",
  "I suddenly noticed everybody around me is weak, It's my choice to not have any friends, most people just can't keep up with the grindset.",
  'If you don’t take free food out of the sky you’ll never grind to be a grillionaire. Always take your opportunities when you have them.',
  "Don't tell me what to do",
  'Ignore irony, it just gets in the way of your grind',
  "You're not that guy pal, trust me.",
  "Don't drive past accidents, be the one that causes them.",
  "Drive past accidents. Don't take your eyes off the bag.",
  'Stop taking your schizophrenia pills. Go insane',
  'Wear a mask not just to hide your insecurities, but also to prevent you getting caught for several homicides',
  'W*men will interrupt your grind, keep them out of your life.',
  "The only laundry I do is when I'm laundering all this money",
  'Show a complete lack of remorse',
  'Only a true Sigma can disguise himself as a Beta and endure the insults of being Beta to secure the bag and stay on his grind. ',
  "I kill people so that they don't have to die on their own",
  'True sigma males commit horrific acts toward their enemies and don’t hesitate to take their life to deny the beta international community the satisfaction of seeing them face justice',
  'Sigma confesses love for himself as well',
  'Compass can lead to treasure, Woman can lead to disaster',
  "Don't let a women ruin your life , ruin it yourself",
  'All women are inferior to men',
]

const AUTHORS = [
  'Sigma Imortillionaire',
  'Dodecillionaire Sigma',
  'Sigma Male',
  'Evangelionaire Sigma',
  'Sigma Millionaire',
  'Quadrillionaire Sigma Male',
  'Sigma Trillionaire',
  'Quintillionare Sigma Male',
  'Octillionaire Sigma',
  'Sigma Sun Tzu',
]

export default function handler(req, res) {
  res.status(200).json({ quote: getRandomItemFromArray(QUOTES), author: getRandomItemFromArray(AUTHORS) })
}
