import getRandomItemFromArray from '../../getRandomItemFromArray'

const VIDEOS = [
  'https://www.youtube.com/watch?v=QCCkSJXdZu8',
  'https://www.youtube.com/watch?v=Ibj-XDpSisA',
  'https://www.youtube.com/watch?v=bWvVVLFk1G0',
  'https://www.youtube.com/watch?v=38un4cjoHco',
  'https://www.youtube.com/watch?v=AdrhrKNCfl8',
  'https://www.youtube.com/watch?v=vkWXkYbggPU',
  'https://www.youtube.com/watch?v=0dS1cqUbF50',
  'https://www.youtube.com/watch?v=xfSZKITmU1M',
  'https://www.youtube.com/watch?v=BJLG-Q85lb4',
  'https://www.youtube.com/watch?v=llNixbs2KZs',
  'https://www.youtube.com/watch?v=eDk_Tmt6it0',
  'https://www.youtube.com/watch?v=IdXvg45EUWE',
  'https://www.youtube.com/watch?v=kYEooyVQ1yw',
  'https://www.youtube.com/watch?v=61TCyN1uRXI',
  'https://www.youtube.com/watch?v=EDB4z-6u40g',
  'https://www.youtube.com/watch?v=1Jp8xVClkBQ',
  'https://www.youtube.com/watch?v=GJVR2-VrmmE',
  'https://www.youtube.com/watch?v=MplqnWm5PH0',
  'https://www.youtube.com/watch?v=dMxI3M_v3-s',
  'https://www.youtube.com/watch?v=qZrHVWGJdd4',
  'https://www.youtube.com/watch?v=NBxhrpbL79c',
  'https://www.youtube.com/watch?v=Fu1TO8K2SJ8',
  'https://www.youtube.com/watch?v=g7JSq4A5f-Y',
  'https://www.youtube.com/watch?v=iVonUBSZSYs',
  'https://www.youtube.com/watch?v=1RjhPJL3W1A',
  'https://www.youtube.com/watch?v=JIjXi89ouwo',
  'https://www.youtube.com/watch?v=4k23yLG_1_k',
  'https://www.youtube.com/watch?v=0zWnIvGMs2g',
  'https://www.youtube.com/watch?v=7poGNxzv7oY',
  'https://www.youtube.com/watch?v=dn9EqeMPxWw',
  'https://www.youtube.com/watch?v=VO91Wsrr5N4',
  'https://www.youtube.com/watch?v=_P_KljJkcvs',
  'https://www.youtube.com/watch?v=gQuWT47PWAY',
  'https://www.youtube.com/watch?v=pM80bQi2IKU',
  'https://www.youtube.com/watch?v=AFTA7h1ssdY',
  'https://www.youtube.com/watch?v=xYjE3vdzs40',
  'https://www.youtube.com/watch?v=aIQwUbCxtgw',
  'https://www.youtube.com/watch?v=37V4ZjR2niw',
  'https://www.youtube.com/watch?v=-WH9EBS7JwY',
  'https://www.youtube.com/watch?v=hasw2PP7jvE',
  'https://www.youtube.com/watch?v=Bt_xk9y4_g0',
  'https://www.youtube.com/watch?v=63YE-RKnihQ',
  'https://www.youtube.com/watch?v=R4Sj7j7Gy8A',
  'https://www.youtube.com/watch?v=yUeLMymbff8',
  'https://www.youtube.com/watch?v=aezel8OcKJg',
  'https://www.youtube.com/watch?v=xwVxKclc7wQ',
  'https://www.youtube.com/watch?v=6T5tQ93gUcQ',
  'https://www.youtube.com/watch?v=AOD8_pEpyR0',
  'https://www.youtube.com/watch?v=cCyQ75EJtrs',
  'https://www.youtube.com/watch?v=s4U62XTFD9w',
]

export default function handler(req, res) {
  res.status(200).json({ url: getRandomItemFromArray(VIDEOS) })
}
